#  ▀█▀ █░█ █▀▀ █▀▄▀█ █▀▀
#  ░█░ █▀█ ██▄ █░▀░█ ██▄
# GTK Theme
env = GTK_THEME, Catppuccin-Mocha
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland

# Cursor theme
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 20

# QT Theme
env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_QPA_PLATFORMTHEME, qt6ct

# Icon theme
env = XDG_ICON_THEME, Tela-circle-dracula

# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

decoration {
    dim_special = 0.3
    blur {
        special = true
    }
}

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 3
    col.active_border = rgb(b4befe) rgb(f5c2e7) 45deg
	col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar