background {{colors.background.default.hex}}
foreground {{colors.on_background.default.hex}}
cursor {{colors.primary.default.hex}}
selection_background {{colors.secondary.default.hex}}
selection_foreground {{colors.on_secondary.default.hex}}
